/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.event.ListSelectionListener;
import model.Buku;

/**
 *
 * @author farhannivta
 */
public class MainFrame extends javax.swing.JFrame implements MainView {
    private BukuTableModel bukuTableModel = null;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.searchByComboBox.removeAllItems();
        this.searchByComboBox.addItem("id");
        this.searchByComboBox.addItem("judul");
        this.searchByComboBox.addItem("genre");
        this.searchByComboBox.addItem("penulis");
        this.searchByComboBox.addItem("penerbit");
        this.searchByComboBox.addItem("lokasi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        idTextField = new javax.swing.JTextField();
        judulTextField = new javax.swing.JTextField();
        genreTextField = new javax.swing.JTextField();
        penulisTextField = new javax.swing.JTextField();
        penerbitTextField = new javax.swing.JTextField();
        lokasiTextField = new javax.swing.JTextField();
        stockTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tampilSemuaButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        searchByComboBox = new javax.swing.JComboBox<>();
        cariButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Perpustakaan Umum Yogyakarta");

        jLabel2.setText("ID");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Genre Buku");

        jLabel5.setText("Penulis Buku");

        jLabel6.setText("Penerbit Buku");

        jLabel7.setText("Lokasi Buku");

        jLabel8.setText("Stock Buku");

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookTable);

        idTextField.setEditable(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        judulTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulTextFieldActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");

        updateButton.setText("Update");

        hapusButton.setText("Hapus");

        tampilSemuaButton.setText("Tampilkan Semua");

        jLabel9.setText("Cari Buku");

        searchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchByComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByComboBoxActionPerformed(evt);
            }
        });

        cariButton.setText("Cari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stockTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(lokasiTextField)
                            .addComponent(penerbitTextField)
                            .addComponent(penulisTextField)
                            .addComponent(genreTextField)
                            .addComponent(judulTextField)
                            .addComponent(idTextField))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampilSemuaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(penulisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tampilSemuaButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(penerbitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lokasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void judulTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulTextFieldActionPerformed

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked

    }//GEN-LAST:event_simpanButtonMouseClicked

    private void searchByComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookTable;
    private javax.swing.JButton cariButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JTextField lokasiTextField;
    private javax.swing.JTextField penerbitTextField;
    private javax.swing.JTextField penulisTextField;
    private javax.swing.JComboBox<String> searchByComboBox;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JButton tampilSemuaButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setDataBukuTable(List<Buku> books) {
        BukuTableModel bukuTableModel = new BukuTableModel();
        bukuTableModel.setBooks(books);
        this.BookTable.setModel(bukuTableModel);
    }

    @Override
    public void setJudulTextField(String judul) {
        this.judulTextField.setText(judul);
    }

    @Override
    public String getJudulTextField() {
        return this.judulTextField.getText();
    }

    @Override
    public void setGenreTextField(String genre) {
        this.genreTextField.setText(genre);
    }

    @Override
    public String getGenreTextField() {
        return this.genreTextField.getText();
    }

    @Override
    public void setPenulisTextField(String penulis) {
        this.penulisTextField.setText(penulis);
    }

    @Override
    public String getPenulisTextField() {
        return this.penulisTextField.getText();
    }

    @Override
    public void setPenerbitTextField(String penerbit) {
        this.penerbitTextField.setText(penerbit);
    }

    @Override
    public String getPenerbitTextField() {
        return this.penerbitTextField.getText();
    }

    @Override
    public void setLocationTextField(String location) {
        this.lokasiTextField.setText(location);
    }

    @Override
    public String getLocationTextField() {
        return this.lokasiTextField.getText();
    }

    @Override
    public void setStcokTextField(String stock) {
        this.stockTextField.setText(stock);
    }

    @Override
    public String getStockTextField() {
        return this.stockTextField.getText();
    }

    @Override
    public void setIdTextField(String id) {
        this.idTextField.setText(id);
    }

    @Override
    public String getIdTextField() {
        return this.idTextField.getText();
    }

    @Override
    public void setBukuTableClickListener(ListSelectionListener listener) {
        this.BookTable.getSelectionModel().addListSelectionListener(listener);
    }

    @Override
    public int getSelectedRowIndex() {
        return this.BookTable.getSelectedRow();
    }

    @Override
    public Buku getBookByRow(int row) {
        Buku book = new Buku();
        book.id = (int) this.BookTable.getValueAt(row, 0);
        book.judul = (String) this.BookTable.getValueAt(row, 1);
        book.genre = (String) this.BookTable.getValueAt(row, 2);
        book.penulis = (String) this.BookTable.getValueAt(row, 3);
        book.penerbit = (String) this.BookTable.getValueAt(row, 4);
        book.lokasi = (String) this.BookTable.getValueAt(row, 5);
        book.stock = (int) this.BookTable.getValueAt(row, 6);
        
        return book;
    }

    @Override
    public void addClearListener(ActionListener listener) {
        this.clearButton.addActionListener(listener);
    }

    @Override
    public void addSimpanListener(ActionListener listener) {
        this.simpanButton.addActionListener(listener);
    }

    @Override
    public void addUpdateListener(ActionListener listener) {
        this.updateButton.addActionListener(listener);
    }

    @Override
    public void addHapusListener(ActionListener listener) {
        this.hapusButton.addActionListener(listener);
    }

    @Override
    public void setSearchTextField(String search) {
        this.searchTextField.setText(search);
    }

    @Override
    public String getSearchTextField() {
        return this.searchTextField.getText();
    }

    @Override
    public String getSearchByComboBox() {
        return this.searchByComboBox.getSelectedItem().toString();
    }

    @Override
    public void addCariListener(ActionListener listener) {
        this.cariButton.addActionListener(listener);
    }

    @Override
    public void addTampilSemuaListener(ActionListener listener) {
        this.tampilSemuaButton.addActionListener(listener);
    }
}
